using System;
using System.IO;
using System.Text.Json;
using System.Collections.Generic;

class BlockModelGenerator
{
    static void Main()
    {
        string[] blocks = {
            "air", "grass", "dirt", "stone", "water", "sand", "wood", "leaves", 
            "door", "dooropen", "chest", "coal", "iron", "crafting_table", 
            "glass", "bedrock", "gravel", "plank", "gold", "diamond"
        };

        string outputDir = @"C:\Users\Redacted\Documents\RedactedCraft\Assets\models";
        Directory.CreateDirectory(outputDir);

        foreach (var block in blocks)
        {
            if (block == "air") continue;

            var model = new
            {
                format_version = "1.21.11",
                credit = "Generated by RedactedCraft Tools",
                texture_size = new[] { 48, 32 },
                textures = new
                {
                    @_0 = $"Assets:blocks/{block}",
                    particle = $"Assets:blocks/{block}"
                },
                elements = new[]
                {
                    new
                    {
                        from = new[] { 0, 0, 0 },
                        to = new[] { 16, 16, 16 },
                        faces = new Dictionary<string, object>
                        {
                            { "north", new { uv = new[] { 0.66667, 0.5, 1.0, 1.0 }, texture = "#0" } }, // (2,1)
                            { "east",  new { uv = new[] { 0.0, 0.0, 0.33333, 0.5 }, texture = "#0" } }, // (0,0)
                            { "south", new { uv = new[] { 0.33333, 0.5, 0.66667, 1.0 }, texture = "#0" } }, // (1,1)
                            { "west",  new { uv = new[] { 0.33333, 0.0, 0.66667, 0.5 }, texture = "#0" } }, // (1,0)
                            { "up",    new { uv = new[] { 0.66667, 0.0, 1.0, 0.5 }, texture = "#0" } }, // (2,0)
                            { "down",  new { uv = new[] { 0.0, 0.5, 0.33333, 1.0 }, texture = "#0" } } // (0,1)
                        }
                    }
                },
                display = new
                {
                    thirdperson_righthand = new { scale = new[] { 0.3457, 0.3457, 0.3457 } },
                    thirdperson_lefthand = new { scale = new[] { 0.3457, 0.3457, 0.3457 } },
                    firstperson_righthand = new { scale = new[] { 0.3457, 0.3457, 0.3457 } },
                    firstperson_lefthand = new { scale = new[] { 0.3457, 0.3457, 0.3457 } },
                    ground = new { translation = new[] { 0, 3, 0 }, scale = new[] { 0.3457, 0.3457, 0.3457 } },
                    gui = new { rotation = new[] { 25.22, -32.01, -4.14 }, scale = new[] { 0.52539, 0.52539, 0.52539 } },
                    head = new { scale = new[] { 0.3457, 0.3457, 0.3457 } }
                }
            };

            var options = new JsonSerializerOptions { WriteIndented = true };
            string json = JsonSerializer.Serialize(model, options).Replace("\"_0\":", "\"0\":");
            File.WriteAllText(Path.Combine(outputDir, $"{block}.json"), json);
        }

        Console.WriteLine($"Generated models for {blocks.Length - 1} blocks in {outputDir}");
    }
}
