namespace LatticeVeilMonoGame.Core;

// Block IDs are stored as bytes in chunk data.
// Note: Water remains at 4 for backward compatibility with existing worlds.
public enum BlockId : byte
{
    Air = 0,
    Grass = 1,
    Dirt = 2,
    Stone = 3,
    Water = 4,
    Sand = 5,
    Wood = 6,
    Leaves = 7,
    // 8-9 reserved
    Chest = 10,
    Coal = 11,
    Iron = 12,
    ArtificerBench = 13,
    ArtificersWorkbench = ArtificerBench,
    CraftingTable = ArtificerBench,
    Glass = 14,
    Nullrock = 15,
    Nullblock = Nullrock,
    Corestone = Nullrock,
    Gravel = 16,
    Plank = 17,
    Gold = 18,
    Diamond = 19,
    Runestone = 20,
    Veinstone = 21,
    Veilglass = 22,
    Gravestone = 23,
    InscribedTablet = 24,
    FragmentScrap = 25,
    VeilSealStone = 26,
    EchoBloom = 27,
    GraveSilt = 28,
    RunestoneDust = 29,
    VeinstoneCrystal = 30,
    AnchoringSalt = 31,
    StabilizedAsh = 32,
    EchoIconShard = 33,
    CopperWiring = 34,
    LimiterSigil = 35,
    AlignmentMatrixFragment = 36,
    AttunedKeystoneFragment = 37,
    RegulatorComponent = 38,
    TransitRegulatorPart = 39,
    WayfinderPlinthPart = 40,
    ResonanceCore = 41,
    AxiomFulgrite = 42,
    AnchoringAlloy = 43,
    CleanPhial = 44,
    Swiftleaf = 45,
    Driftcap = 46,
    Embermoss = 47,
    SigilLoom = 48,
    QuietAlembic = 49,
    RunicAnvil = 50,
    CinderbranchStaff = 51,
    StormreedStaff = 52,
    WayboundFrame = 53,
    AttunedKeystone = 54,
    TimedLimiter = 55,
    TransitRegulator = 56,
    WaygatePlinth = 57,
    WaygateRune = 58,
    EvergateCore = 59,
    EvergateCoreUnstable = 60,
    FleetstepDraught = 61,
    SkyboundPhilter = 62,
    PyroskinTonic = 63,
    BrineveilElixir = 64,
    WaterBucket = 65,
}
