namespace LatticeVeilMonoGame.Core;

// Keep these byte values aligned with legacy inventory saves while inventory is migrating off BlockId.
public enum ItemId : byte
{
    None = 0,
    GrassBlock = 1,
    DirtBlock = 2,
    StoneBlock = 3,
    Water = 4,
    SandBlock = 5,
    OakLog = 6,
    LeavesBlock = 7,
    Chest = 10,
    CoalOreBlock = 11,
    IronOreBlock = 12,
    ArtificerBench = 13,
    GlassBlock = 14,
    NullrockBlock = 15,
    GravelBlock = 16,
    OakPlanks = 17,
    GoldOreBlock = 18,
    DiamondBlock = 19,

    Runestone = 20,
    Veinstone = 21,
    Veilglass = 22,
    Gravestone = 23,
    InscribedTablet = 24,
    FragmentScrap = 25,
    VeilSealStone = 26,
    EchoBloom = 27,
    GraveSilt = 28,
    RunestoneDust = 29,
    VeinstoneCrystal = 30,
    AnchoringSalt = 31,
    StabilizedAsh = 32,
    EchoIconShard = 33,
    CopperWiring = 34,
    LimiterSigil = 35,
    AlignmentMatrixFragment = 36,
    AttunedKeystoneFragment = 37,
    RegulatorComponent = 38,
    TransitRegulatorPart = 39,
    WayfinderPlinthPart = 40,
    ResonanceCore = 41,
    AxiomFulgrite = 42,
    AnchoringAlloy = 43,
    CleanPhial = 44,
    Swiftleaf = 45,
    Driftcap = 46,
    Embermoss = 47,
    SigilLoom = 48,
    QuietAlembic = 49,
    RunicAnvil = 50,
    CinderbranchStaff = 51,
    StormreedStaff = 52,
    WayboundFrame = 53,
    AttunedKeystone = 54,
    TimedLimiter = 55,
    TransitRegulator = 56,
    WaygatePlinth = 57,
    WaygateRune = 58,
    EvergateCore = 59,
    EvergateCoreUnstable = 60,

    FleetstepDraught = 61,
    SkyboundPhilter = 62,
    PyroskinTonic = 63,
    BrineveilElixir = 64,

    WaterBucket = 65,
    PlantFiber = 66,
    CoalChunk = 67,
    IronBlock = 68,
    GoldBlock = 69,
    DiamondBuildingBlock = 70,
    EmptyBucket = 71,
    Stick = 72,
    Torch = 73,
    FiberWrappedTorch = 74,
    BasicKiln = 75,
    AdvancedKiln = 76,
    FieldOven = 77,
    IronBillet = 78,
    GoldBillet = 79,
    DiamondGem = 87,
    Pebbles = 88,
    CopperOreBlock = 89,
    IronCluster = 90,
    GoldCluster = 91,
    CopperCluster = 92,
    CopperBillet = 93,
    EmeraldOreBlock = 94,
    RubyOreBlock = 95,
    SapphireOreBlock = 96,
    AmethystOreBlock = 97,
    Emerald = 98,
    RubyStone = 99,
    SapphireGem = 100,
    AmethystShard = 101,
    ForestBerries = 105,
    PlantRation = 106,
    CookedRation = 107,

    WoodMattock = 108,
    StoneMattock = 109,
    IronMattock = 110,
    DiamondMattock = 111,
    WoodPickaxe = WoodMattock,
    StonePickaxe = StoneMattock,
    IronPickaxe = IronMattock,
    DiamondPickaxe = DiamondMattock,

    WoodHatchet = 112,
    StoneHatchet = 113,
    IronHatchet = 114,
    DiamondHatchet = 115,
    WoodAxe = WoodHatchet,
    StoneAxe = StoneHatchet,
    IronAxe = IronHatchet,
    DiamondAxe = DiamondHatchet,

    WoodSpade = 116,
    StoneSpade = 117,
    IronSpade = 118,
    DiamondSpade = 119,
    WoodShovel = WoodSpade,
    StoneShovel = StoneSpade,
    IronShovel = IronSpade,
    DiamondShovel = DiamondSpade,

    WoodBlade = 120,
    StoneBlade = 121,
    IronBlade = 122,
    DiamondBlade = 123,

    WoodPlow = 124,
    StonePlow = 125,
    IronPlow = 126,
    DiamondPlow = 127,

    WoodJavelin = 128,
    StoneJavelin = 129,
    IronJavelin = 130,
    DiamondJavelin = 131,
    SleepingBag = 132,
}
