<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <AssemblyTitle>LatticeVeil Installer</AssemblyTitle>
    <AssemblyDescription>Custom installer for LatticeVeil</AssemblyDescription>
    <AssemblyVersion>14.0.1.0</AssemblyVersion>
    <FileVersion>14.0.1.0</FileVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishDir>..\FINAL</PublishDir>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <StartupObject>LatticeVeilInstaller.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.IO.Compression" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="MainWindow.xaml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\LatticeVeilUninstaller\bin\Release\net8.0-windows\win-x64\publish\LatticeVeilUninstaller.exe" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Icon.ico" />
  </ItemGroup>

</Project>
